<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-HSPQSV91" failures="1" tests="3" name="Com.HelloFresh.ScreenshotTest" time="241.732" errors="0" timestamp="28 Aug 2018 22:29:46 GMT" skipped="0">
  <testcase classname="Com.HelloFresh.ScreenshotTest" name="setUp" time="32.720"/>
  <testcase classname="Com.HelloFresh.ScreenshotTest" name="logInTest" time="205.717">
    <failure message="MY ACCOUNT" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: MY ACCOUNT
at org.testng.Assert.fail(Assert.java:96)
at Com.HelloFresh.ScreenshotTest.logInTest(ScreenshotTest.java:66)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:844)
]]>
    </failure>
  </testcase> <!-- logInTest -->
  <testcase classname="Com.HelloFresh.ScreenshotTest" name="LogOut" time="3.295"/>
</testsuite> <!-- Com.HelloFresh.ScreenshotTest -->
